<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31" started-at="2015-06-23T20:05:56Z" finished-at="2015-06-23T20:05:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31" started-at="2015-06-23T20:05:56Z" finished-at="2015-06-23T20:05:56Z">
      <class name="testscripts.scenario1.JCrewInvalidSignupEmail">
        <test-method status="PASS" signature="suiteSetup(org.testng.ITestContext)[pri:0, instance:testscripts.scenario1.JCrewInvalidSignupEmail@7006c658]" name="suiteSetup" is-config="true" duration-ms="47" started-at="2015-06-23T16:05:56Z" finished-at="2015-06-23T16:05:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@573f2bb1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteSetup -->
        <test-method status="FAIL" signature="runTC1()[pri:0, instance:testscripts.scenario1.JCrewInvalidSignupEmail@7006c658]" name="runTC1" duration-ms="15" started-at="2015-06-23T16:05:56Z" finished-at="2015-06-23T16:05:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at supportlibraries.DriverScript.getListOfTools(DriverScript.java:124)
	at supportlibraries.DriverScript.startUp(DriverScript.java:149)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:94)
	at testscripts.scenario1.JCrewInvalidSignupEmail.runTC1(JCrewInvalidSignupEmail.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTC1 -->
        <test-method status="PASS" signature="testMethodSetup()[pri:0, instance:testscripts.scenario1.JCrewInvalidSignupEmail@7006c658]" name="testMethodSetup" is-config="true" duration-ms="0" started-at="2015-06-23T16:05:56Z" finished-at="2015-06-23T16:05:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodSetup -->
        <test-method status="FAIL" signature="testMethodTearDown()[pri:0, instance:testscripts.scenario1.JCrewInvalidSignupEmail@7006c658]" name="testMethodTearDown" is-config="true" duration-ms="0" started-at="2015-06-23T16:05:56Z" finished-at="2015-06-23T16:05:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.cognizant.framework.Report.updateResultSummary(Report.java:263)
	at supportlibraries.TestCase.testMethodTearDown(TestCase.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodTearDown -->
        <test-method status="SKIP" signature="suiteTearDown()[pri:0, instance:testscripts.scenario1.JCrewInvalidSignupEmail@7006c658]" name="suiteTearDown" is-config="true" duration-ms="0" started-at="2015-06-23T16:05:56Z" finished-at="2015-06-23T16:05:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteTearDown -->
      </class> <!-- testscripts.scenario1.JCrewInvalidSignupEmail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
